version: '3'
services:
    front:
        volumes:
            - "./front/:/home/app/"
        container_name: front
        command: sh -c "cd /home/app && npm install --save && npm start"
        image: bayesimpact/react-base

        ports:
            - "3000:3000"  
    api:
        volumes:
            - "./api/:/home/app/"
        container_name: api
        command: sh -c "cd /home/app && npm install --save && npm start"
        image: node:9.4.0-alpine
        ports:
            - "8080:8080"
